/*
 * This file is automatically generated!
 * Do not edit this file!
 *
 * This is the java file of the ivy data class progressMessage with the namespace ch.xpertline.xtrans.excel
 */
package ch.xpertline.xtrans.excel;

/**
 */
public class ProgressMessage extends ch.ivyteam.ivy.scripting.objects.CompositeObject
{
  /** SerialVersionUID */
  private static final long serialVersionUID = 3968555253302051005L;

  public static final int ERROR_MESSAGE = 1;
  public static final int SUCCESS_MESSAGE = 0;
  public static final int INFORMATION_MESSAGE = 2;
  /**
   */
  private java.lang.Number type;

  /**
   * Gets the field type.
   * @return the value of the field type; may be null.
   */
  public java.lang.Number getType()
  {
    return type;
  }

  /**
   * Sets the field type.
   * @param _type the new value of the field type.
   */
  public void setType(java.lang.Number _type)
  {
    type = _type;
  }

  /**
   */
  private java.lang.String text;

  /**
   * Gets the field text.
   * @return the value of the field text; may be null.
   */
  public java.lang.String getText()
  {
    return text;
  }

  /**
   * Sets the field text.
   * @param _text the new value of the field text.
   */
  public void setText(java.lang.String _text)
  {
    text = _text;
  }

}
